name: Mutation Test
on: workflow_dispatch

jobs:
  Test-load:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Fetching node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Execute mutation test
        run: make test/mutation 